# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'DatnaManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 5.0.0-rc.3'
	pod 'AFNetworking', '~> 3.0'
  # Pods for DatnaManagement

end
